'use client'

import { createContext, useContext, useState, ReactNode, memo } from 'react'

type Language = 'id' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Layanan',
    'nav.portfolio': 'Portfolio',
    'nav.about': 'Tentang',
    'nav.experience': 'Pengalaman',
    'nav.joinMember': 'Join Member',
    'nav.contact': 'Hubungi Kami',

    // Home
    'home.tagline': 'Architecture Collaboration',
    'home.viewPortfolio': 'Lihat Portfolio',
    'home.freeConsultation': 'Konsultasi Gratis',
    'home.projectsCompleted': 'Proyek Selesai',
    'home.yearsExperience': 'Tahun Pengalaman',

    // Services
    'services.title': 'Solusi Arsitektur Komprehensif',
    'services.description': 'Dari konsep hingga realisasi, kami menyediakan layanan desain arsitektur lengkap untuk berbagai kebutuhan',
    'services.backToHome': 'Kembali ke Home',
    'services.services': 'Layanan Kami',
    'services.interiorDesign': 'Desain Interior',
    'services.exteriorDesign': 'Desain Exterior',
    'services.startingFrom': 'Mulai dari',
    'services.learnMore': 'Pelajari Lebih Lanjut',
    'services.order': 'Pesan Sekarang',
    'services.ctaTitle': 'Siap Memulai Proyek Anda?',
    'services.ctaDescription': 'Hubungi kami untuk konsultasi gratis dan diskusikan visi arsitektur Anda',
    'services.ctaButton': 'Hubungi Kami',
    // Service Items
    'services.residential.title': 'Rumah Tinggal',
    'services.residential.description': 'Desain hunian modern yang fungsional dan estetis',
    'services.residential.feature1': 'Desain Custom',
    'services.residential.feature2': '3D Rendering',
    'services.residential.feature3': 'RAB Detail',
    'services.residential.feature4': 'Site Visit',
    'services.residential.feature5': 'Material Selection',
    'services.apartment.title': 'Apartment',
    'services.apartment.description': 'Interior dan eksterior apartemen dengan konsep minimalis',
    'services.apartment.feature1': 'Space Planning',
    'services.apartment.feature2': 'Material Selection',
    'services.apartment.feature3': 'Lighting Design',
    'services.apartment.feature4': 'Furniture Layout',
    'services.apartment.feature5': 'Smart Home',
    'services.hotel.title': 'Hotel & Resort',
    'services.hotel.description': 'Desain hospitality yang mengutamakan guest experience',
    'services.hotel.feature1': 'Concept Design',
    'services.hotel.feature2': 'Room Planning',
    'services.hotel.feature3': 'Public Area',
    'services.hotel.feature4': 'Landscape',
    'services.hotel.feature5': 'Brand Identity',
    'services.commercial.title': 'Commercial',
    'services.commercial.description': 'Mall, office, dan retail space yang produktif',
    'services.commercial.feature1': 'Zoning Strategy',
    'services.commercial.feature2': 'Traffic Flow',
    'services.commercial.feature3': 'Brand Identity',
    'services.commercial.feature4': 'Wayfinding',
    'services.commercial.feature5': 'Accessibility',
    'services.villa.title': 'Villa',
    'services.villa.description': 'Villa mewah dengan integrasi alam dan modern',
    'services.villa.feature1': 'Resort Style',
    'services.villa.feature2': 'Pool Design',
    'services.villa.feature3': 'Outdoor Living',
    'services.villa.feature4': 'Green Design',
    'services.villa.feature5': 'Privacy Focus',
    'services.cafe.title': 'Cafe & Restaurant',
    'services.cafe.description': 'Cafe dan restoran dengan konsep unik dan menarik',
    'services.cafe.feature1': 'Destination Concept',
    'services.cafe.feature2': 'Cultural Elements',
    'services.cafe.feature3': 'Landscape Design',
    'services.cafe.feature4': 'Sustainability',
    'services.cafe.feature5': 'Guest Experience',

    // Portfolio
    'portfolio.title': 'Karya Terbaik Kami',
    'portfolio.description': 'Lihat bagaimana kami mewujudkan visi klien menjadi ruang yang inspiratif dan fungsional',
    'portfolio.ctaTitle': 'Tertarik dengan Proyek Kami?',
    'portfolio.ctaDescription': 'Mari diskusikan bagaimana kami bisa membantu mewujudkan visi arsitektur Anda',
    'portfolio.startConsultation': 'Mulai Konsultasi',
    'portfolio.viewServices': 'Lihat Layanan Kami',

    // About
    'about.pageTitle': 'Tentang',
    'about.title': 'Arsitek Berpengalaman',
    'about.description': 'Mengenal lebih dekat tim dan visi kami dalam menciptakan ruang yang inspiratif',
    'about.contactMe': 'Hubungi Saya',
    'about.viewPortfolio': 'Lihat Portfolio',
    'about.projectsCompleted': 'Proyek Selesai',
    'about.yearsExperience': 'Tahun Pengalaman',
    'about.satisfiedClients': 'Klien Puas',
    'about.awards': 'Penghargaan',
    'about.education': 'Pendidikan',
    'about.skillsCertifications': 'Keahlian & Sertifikasi',
    'about.certifications': 'Sertifikasi',
    'about.contactInfo': 'Informasi Kontak',
    'about.phone': 'Telepon',
    'about.email': 'Email',
    'about.address': 'Alamat',

    // Experience
    'experience.title': 'Perjalanan Profesional',
    'experience.description': 'Pengalaman kerja, pencapaian, dan kontribusi dalam dunia arsitektur',
    'experience.workHistory': 'Riwayat Pekerjaan',
    'experience.ctaTitle': 'Tertarik Bekerja Sama?',
    'experience.ctaDescription': 'Mari diskusikan proyek Anda dan rasakan pengalaman kerja profesional dengan kami',

    // Contact
    'contact.title': 'Mari Berkolaborasi',
    'contact.description': 'Siap mewujudkan visi arsitektur Anda? Hubungi kami untuk konsultasi gratis',
    'contact.info': 'Informasi Kontak',
    'contact.infoDescription': 'Hubungi kami melalui salah satu cara berikut. Tim kami siap membantu menjawab pertanyaan dan mendiskusikan proyek Anda.',
    'contact.phoneNumber': 'Telepon',
    'contact.workingHours': 'Senin - Jumat, 09:00 - 17:00',
    'contact.responseTime': 'Respon dalam 24 jam',
    'contact.email': 'Email',
    'contact.address': 'Alamat',
    'contact.operatingHours': 'Jam Operasional',
    'contact.mondayFriday': 'Senin - Jumat',
    'contact.saturday': 'Sabtu',
    'contact.sunday': 'Minggu',
    'contact.closed': 'Tutup',
    'contact.sendMessage': 'Kirim Pesan',
    'contact.formDescription': 'Isi formulir di bawah untuk konsultasi gratis',
    'contact.name': 'Nama',
    'contact.yourName': 'Nama Anda',
    'contact.emailAddress': 'Email',
    'contact.emailPlaceholder': 'email@example.com',
    'contact.projectType': 'Jenis Proyek',
    'contact.selectProjectType': 'Pilih jenis proyek',
    'contact.projectResidential': 'Rumah Tinggal',
    'contact.projectApartment': 'Apartment',
    'contact.projectHotel': 'Hotel & Resort',
    'contact.projectCommercial': 'Commercial',
    'contact.projectVilla': 'Villa',
    'contact.projectCafe': 'Cafe & Restaurant',
    'contact.projectOther': 'Lainnya',
    'contact.message': 'Pesan',
    'contact.messagePlaceholder': 'Ceritakan tentang proyek Anda...',
    'contact.submitMessage': 'Kirim Pesan',
    'contact.responseEmail': 'Respon Email',
    'contact.initialConsultation': 'Konsultasi Awal',
    'contact.loading': 'Memuat data...',
    // Calculator
    'contact.calculator.simulation': 'Simulasi',
    'contact.calculator.title': 'Kalkulator Budget Proyek',
    'contact.calculator.subtitle': 'Estimasi biaya desain berdasarkan standar fee IAI',
    'contact.calculator.projectParameter': 'Parameter Proyek',
    'contact.calculator.projectParameterDesc': 'Isi detail proyek Anda untuk estimasi',
    'contact.calculator.designCategory': 'Kategori Desain',
    'contact.calculator.architecture': 'Arsitektur',
    'contact.calculator.architectureSub': 'Bangunan Lengkap',
    'contact.calculator.interior': 'Interior',
    'contact.calculator.interiorSub': 'Ruang Dalam',
    'contact.calculator.facade': 'Desain Fasad',
    'contact.calculator.facadeSub': 'Fasad Bangunan',
    'contact.calculator.landscape': 'Landscape',
    'contact.calculator.landscapeSub': 'Taman & Area',
    'contact.calculator.buildingCategory': 'Kategori Bangunan',
    'contact.calculator.buildingArea': 'Luas Bangunan (m²)',
    'contact.calculator.designArea': 'Luas Area Desain (m²)',
    'contact.calculator.areaPlaceholder': 'Masukkan luas dalam m²',
    'contact.calculator.calculateBudget': 'Hitung Budget',
    'contact.calculator.calculate': 'Hitung',
    'contact.calculator.reset': 'Reset',
    'contact.calculator.enterArea': 'Masukkan luas area...',
    'contact.calculator.resultTitle': 'Hasil Estimasi',
    'contact.calculator.resultDesc': 'Perkiraan biaya untuk proyek Anda',
    'contact.calculator.estimateResult': 'Hasil Estimasi',
    'contact.calculator.estimateDesc': 'Perkiraan biaya desain untuk proyek Anda',
    'contact.calculator.estRabBuilding': 'Estimasi RAB Bangunan',
    'contact.calculator.estRabFacade': 'Estimasi RAB Fasad',
    'contact.calculator.feeArchitect': 'Fee Jasa Arsitek (IAI)',
    'contact.calculator.feeFacade': 'Fee Jasa Desain Fasad',
    'contact.calculator.totalFullPackage': 'Total Full Paket',
    'contact.calculator.totalDesignFee': 'Total Fee Desain',
    'contact.calculator.percentOfRab': '% dari RAB',
    'contact.calculator.ofRAB': '% dari RAB',
    'contact.calculator.preDesignPackage': 'Paket Pra-Desain (15%)',
    'contact.calculator.preDesignDesc': 'Survey, Analisis, Konsep Awal',
    'contact.calculator.preDesign': 'Pra-Desain (15%)',
    'contact.calculator.schematicPackage': 'Paket Desain Skematik & 3D (25%)',
    'contact.calculator.schematicDesc': 'Konsep, Denah, 3D Rendering',
    'contact.calculator.schematicDesign': 'Desain Skematik (25%)',
    'contact.calculator.dedPackage': 'Paket DED Lengkap (60%)',
    'contact.calculator.dedDesc': 'Shop Drawing, Detail Teknis, RAB',
    'contact.calculator.developmentDocuments': 'DED Lengkap (60%)',
    'contact.calculator.constructionCost': 'Biaya Konstruksi (RAB)',
    'contact.calculator.disclaimer': 'Disclaimer: Ini adalah estimasi awal berdasarkan standar fee IAI. Harga final dapat berubah tergantung kompleksitas proyek, lokasi, dan spesifikasi material. Hubungi kami untuk penawaran detail.',
    // Building Categories
    'contact.calculator.k1LowSederhana': 'Kategori 1 - Low-Rise Sederhana',
    'contact.calculator.k2LowMenengah': 'Kategori 2 - Low-Rise Menengah',
    'contact.calculator.k3LowMewah': 'Kategori 3 - Low-Rise Mewah',
    'contact.calculator.k1MiddleSederhana': 'Kategori 1 - Middle-Rise Sederhana',
    'contact.calculator.k2MiddleMenengah': 'Kategori 2 - Middle-Rise Menengah',
    'contact.calculator.k3MiddleMewah': 'Kategori 3 - Middle-Rise Mewah',
    'contact.calculator.k1HighSederhana': 'Kategori 1 - High-Rise Sederhana',
    'contact.calculator.k2HighMenengah': 'Kategori 2 - High-Rise Menengah',
    'contact.calculator.k3HighMewah': 'Kategori 3 - High-Rise Mewah',

    // Footer
    'footer.allRights': 'All rights reserved'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.about': 'About',
    'nav.experience': 'Experience',
    'nav.joinMember': 'Join Member',
    'nav.contact': 'Contact',

    // Home
    'home.tagline': 'Architecture Collaboration',
    'home.viewPortfolio': 'View Portfolio',
    'home.freeConsultation': 'Free Consultation',
    'home.projectsCompleted': 'Projects Completed',
    'home.yearsExperience': 'Years Experience',

    // Services
    'services.title': 'Comprehensive Architecture Solutions',
    'services.description': 'From concept to realization, we provide complete architectural design services for various needs',
    'services.backToHome': 'Back to Home',
    'services.services': 'Our Services',
    'services.interiorDesign': 'Interior Design',
    'services.exteriorDesign': 'Exterior Design',
    'services.startingFrom': 'Starting from',
    'services.learnMore': 'Learn More',
    'services.order': 'Order Now',
    'services.ctaTitle': 'Ready to Start Your Project?',
    'services.ctaDescription': 'Contact us for a free consultation and discuss your architectural vision',
    'services.ctaButton': 'Contact Us',
    // Service Items
    'services.residential.title': 'Residential',
    'services.residential.description': 'Modern and functional home designs with aesthetic appeal',
    'services.residential.feature1': 'Custom Design',
    'services.residential.feature2': '3D Rendering',
    'services.residential.feature3': 'Detailed RAB',
    'services.residential.feature4': 'Site Visit',
    'services.residential.feature5': 'Material Selection',
    'services.apartment.title': 'Apartment',
    'services.apartment.description': 'Interior and exterior apartment design with minimalist concept',
    'services.apartment.feature1': 'Space Planning',
    'services.apartment.feature2': 'Material Selection',
    'services.apartment.feature3': 'Lighting Design',
    'services.apartment.feature4': 'Furniture Layout',
    'services.apartment.feature5': 'Smart Home',
    'services.hotel.title': 'Hotel & Resort',
    'services.hotel.description': 'Hospitality design prioritizing guest experience',
    'services.hotel.feature1': 'Concept Design',
    'services.hotel.feature2': 'Room Planning',
    'services.hotel.feature3': 'Public Area',
    'services.hotel.feature4': 'Landscape',
    'services.hotel.feature5': 'Brand Identity',
    'services.commercial.title': 'Commercial',
    'services.commercial.description': 'Productive malls, offices, and retail spaces',
    'services.commercial.feature1': 'Zoning Strategy',
    'services.commercial.feature2': 'Traffic Flow',
    'services.commercial.feature3': 'Brand Identity',
    'services.commercial.feature4': 'Wayfinding',
    'services.commercial.feature5': 'Accessibility',
    'services.villa.title': 'Villa',
    'services.villa.description': 'Luxury villas with nature integration and modern design',
    'services.villa.feature1': 'Resort Style',
    'services.villa.feature2': 'Pool Design',
    'services.villa.feature3': 'Outdoor Living',
    'services.villa.feature4': 'Green Design',
    'services.villa.feature5': 'Privacy Focus',
    'services.cafe.title': 'Cafe & Restaurant',
    'services.cafe.description': 'Cafe and restaurant with unique and attractive concepts',
    'services.cafe.feature1': 'Destination Concept',
    'services.cafe.feature2': 'Cultural Elements',
    'services.cafe.feature3': 'Landscape Design',
    'services.cafe.feature4': 'Sustainability',
    'services.cafe.feature5': 'Guest Experience',

    // Portfolio
    'portfolio.title': 'Our Best Work',
    'portfolio.description': 'See how we transform our clients\' vision into inspiring and functional spaces',
    'portfolio.ctaTitle': 'Interested in Our Projects?',
    'portfolio.ctaDescription': 'Let\'s discuss how we can help realize your architectural vision',
    'portfolio.startConsultation': 'Start Consultation',
    'portfolio.viewServices': 'View Our Services',

    // About
    'about.pageTitle': 'About',
    'about.title': 'Experienced Architect',
    'about.description': 'Get to know our team and vision in creating inspiring spaces',
    'about.contactMe': 'Contact Me',
    'about.viewPortfolio': 'View Portfolio',
    'about.projectsCompleted': 'Projects Completed',
    'about.yearsExperience': 'Years Experience',
    'about.satisfiedClients': 'Satisfied Clients',
    'about.awards': 'Awards',
    'about.education': 'Education',
    'about.skillsCertifications': 'Skills & Certifications',
    'about.certifications': 'Certifications',
    'about.contactInfo': 'Contact Information',
    'about.phone': 'Phone',
    'about.email': 'Email',
    'about.address': 'Address',

    // Experience
    'experience.title': 'Professional Journey',
    'experience.description': 'Work experience, achievements, and contributions in the world of architecture',
    'experience.workHistory': 'Work History',
    'experience.ctaTitle': 'Interested in Collaborating?',
    'experience.ctaDescription': 'Let\'s discuss your project and experience professional collaboration with us',

    // Contact
    'contact.title': 'Let\'s Collaborate',
    'contact.description': 'Ready to realize your architectural vision? Contact us for a free consultation',
    'contact.info': 'Contact Information',
    'contact.infoDescription': 'Contact us through any of the following methods. Our team is ready to help answer questions and discuss your project.',
    'contact.phoneNumber': 'Phone',
    'contact.workingHours': 'Monday - Friday, 09:00 - 17:00',
    'contact.responseTime': 'Response within 24h',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.operatingHours': 'Operating Hours',
    'contact.mondayFriday': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.closed': 'Closed',
    'contact.sendMessage': 'Send Message',
    'contact.formDescription': 'Fill out the form below for a free consultation',
    'contact.name': 'Name',
    'contact.yourName': 'Your Name',
    'contact.emailAddress': 'Email',
    'contact.emailPlaceholder': 'email@example.com',
    'contact.projectType': 'Project Type',
    'contact.selectProjectType': 'Select project type',
    'contact.projectResidential': 'Residential',
    'contact.projectApartment': 'Apartment',
    'contact.projectHotel': 'Hotel & Resort',
    'contact.projectCommercial': 'Commercial',
    'contact.projectVilla': 'Villa',
    'contact.projectCafe': 'Cafe & Restaurant',
    'contact.projectOther': 'Other',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your project...',
    'contact.submitMessage': 'Send Message',
    'contact.responseEmail': 'Email Response',
    'contact.initialConsultation': 'Initial Consultation',
    'contact.loading': 'Loading data...',
    // Calculator
    'contact.calculator.simulation': 'Simulation',
    'contact.calculator.title': 'Project Budget Calculator',
    'contact.calculator.subtitle': 'Design cost estimation based on IAI fee standards',
    'contact.calculator.projectParameter': 'Project Parameters',
    'contact.calculator.projectParameterDesc': 'Enter your project details for estimation',
    'contact.calculator.designCategory': 'Design Category',
    'contact.calculator.architecture': 'Architecture',
    'contact.calculator.architectureSub': 'Complete Building',
    'contact.calculator.interior': 'Interior',
    'contact.calculator.interiorSub': 'Interior Space',
    'contact.calculator.facade': 'Facade Design',
    'contact.calculator.facadeSub': 'Building Facade',
    'contact.calculator.landscape': 'Landscape',
    'contact.calculator.landscapeSub': 'Garden & Area',
    'contact.calculator.buildingCategory': 'Building Category',
    'contact.calculator.buildingArea': 'Building Area (m²)',
    'contact.calculator.designArea': 'Design Area (m²)',
    'contact.calculator.areaPlaceholder': 'Enter area in m²',
    'contact.calculator.calculateBudget': 'Calculate Budget',
    'contact.calculator.calculate': 'Calculate',
    'contact.calculator.reset': 'Reset',
    'contact.calculator.enterArea': 'Enter area...',
    'contact.calculator.resultTitle': 'Estimation Results',
    'contact.calculator.resultDesc': 'Estimated cost for your project',
    'contact.calculator.estimateResult': 'Estimation Results',
    'contact.calculator.estimateDesc': 'Estimated design cost for your project',
    'contact.calculator.estRabBuilding': 'Estimated RAB Building',
    'contact.calculator.estRabFacade': 'Estimated RAB Facade',
    'contact.calculator.feeArchitect': 'Architect Fee (IAI)',
    'contact.calculator.feeFacade': 'Facade Design Fee',
    'contact.calculator.totalFullPackage': 'Total Full Package',
    'contact.calculator.totalDesignFee': 'Total Design Fee',
    'contact.calculator.percentOfRab': '% of RAB',
    'contact.calculator.ofRAB': '% of RAB',
    'contact.calculator.preDesignPackage': 'Pre-Design Package (15%)',
    'contact.calculator.preDesignDesc': 'Survey, Analysis, Initial Concept',
    'contact.calculator.preDesign': 'Pre-Design (15%)',
    'contact.calculator.schematicPackage': 'Schematic & 3D Design Package (25%)',
    'contact.calculator.schematicDesc': 'Concept, Layout, 3D Rendering',
    'contact.calculator.schematicDesign': 'Schematic Design (25%)',
    'contact.calculator.dedPackage': 'Complete DED Package (60%)',
    'contact.calculator.dedDesc': 'Shop Drawing, Technical Details, RAB',
    'contact.calculator.developmentDocuments': 'Complete DED (60%)',
    'contact.calculator.constructionCost': 'Construction Cost (RAB)',
    'contact.calculator.disclaimer': 'Disclaimer: This is an initial estimate based on IAI fee standards. Final price may vary depending on project complexity, location, and material specifications. Contact us for a detailed quote.',
    // Building Categories
    'contact.calculator.k1LowSederhana': 'Category 1 - Low-Rise Simple',
    'contact.calculator.k2LowMenengah': 'Category 2 - Low-Rise Medium',
    'contact.calculator.k3LowMewah': 'Category 3 - Low-Rise Luxury',
    'contact.calculator.k1MiddleSederhana': 'Category 1 - Middle-Rise Simple',
    'contact.calculator.k2MiddleMenengah': 'Category 2 - Middle-Rise Medium',
    'contact.calculator.k3MiddleMewah': 'Category 3 - Middle-Rise Luxury',
    'contact.calculator.k1HighSederhana': 'Category 1 - High-Rise Simple',
    'contact.calculator.k2HighMenengah': 'Category 2 - High-Rise Medium',
    'contact.calculator.k3HighMewah': 'Category 3 - High-Rise Luxury',

    // Footer
    'footer.allRights': 'All rights reserved'
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('id')

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
